name: Build krb5proxy
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
  permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Rust
      run: | 
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        chmod +x rustup-init.sh
        ./rustup-init.sh -y --default-toolchain stable

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y krb5-user libkrb5-dev

    - name: Build release
      run: ls -ltRa && cargo build --release

    - name: Get tag version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set default version if not tag
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: echo "VERSION=dev-$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Package as tar.gz
      run: |
        mkdir -p dist
        cp target/release/krb5proxy dist/
        tar -czf krb5proxy-${{ env.VERSION }}-linux-x86_64.tar.gz -C dist krb5proxy

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: krb5proxy-${{ env.VERSION }}-linux-x86_64
        path: krb5proxy-${{ env.VERSION }}-linux-x86_64.tar.gz

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          krb5proxy-${{ env.VERSION }}-linux-x86_64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}